Apply WOL only once

diff --git a/epoptes-client/epoptes-client b/epoptes-client/epoptes-client
--- a/epoptes-client/epoptes-client
+++ b/epoptes-client/epoptes-client
@@ -147,7 +147,7 @@ wait_for_dns() {
 
 # Set WoL to the desired state for all currently available Ethernet adapters
 apply_wol() {
-    local tarwol fpath iface
+    local tarwol fpath iface curwol
 
     test "$UID" -eq 0 || return 0
     # Set target WOL to "g" if WOL is unset
@@ -160,7 +160,14 @@ apply_wol() {
         test -f "$fpath" || continue
         iface=${fpath%/address}
         iface=${iface##*/}
-        ethtool -s "$iface" wol "$tarwol"
+        # Avoid setting it again if it's already set
+        curwol=$(ethtool "$iface" | awk '$1 == "Wake-on:" { print $2 }')
+        test "$curwol" != "$tarwol" || continue
+        if ethtool -s "$iface" wol "$tarwol"; then
+            echo "Set WOL=$tarwol for $iface"
+        else
+            echo "Failed to set WOL=$tarwol for $iface"
+        fi
     done
 }
 
