restructure: endsession, get-display.

diff --git a/epoptes-client/get-display b/epoptes-client/get-display
--- a/epoptes-client/get-display
+++ b/epoptes-client/get-display
@@ -1,27 +1,20 @@
 #!/bin/sh
-###########################################################################
-# Output DISPLAY and XAUTHORITY for the current user's X screen.
-# A root user can then use those to access the user's display.
-# Usage: export $(get-display)
-#
-# Copyright (C) 2012 Alkis Georgopoulos <alkisg@gmail.com>
-#
-# This program is free software: you can redistribute it and/or modify
-# it under the terms of the GNU General Public License as published by
-# the Free Software Foundation, either version 3 of the License, or
-# (at your option) any later version.
-#
-# This program is distributed in the hope that it will be useful,
-# but WITHOUT ANY WARRANTY; without even the implied warranty of
-# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-# GNU General Public License for more details.
-#
-# You should have received a copy of the GNU General Public License
-# along with this program.  If not, see <http://www.gnu.org/licenses/>.
-#
-# On Debian GNU/Linux systems, the complete text of the GNU General
-# Public License can be found in `/usr/share/common-licenses/GPL'.
-###########################################################################
+# This file is part of Epoptes, http://epoptes.org
+# Copyright 2012-2018 the Epoptes team, see AUTHORS.
+# SPDX-License-Identifier: GPL-3.0-or-later
+
+usage() {
+    printf "Usage: export \$($0)\n%s" \
+"
+Output DISPLAY and XAUTHORITY for the current user's X screen.
+A root user can then use those to access the user's display.
+"
+}
+
+die() {
+    printf "%s\n" "$@" >&2
+    exit 1
+}
 
 exit_if_found() {
     # Check if DISPLAY/XAUTHORITY are valid.
@@ -37,6 +30,10 @@ exit_if_found() {
         unset DISPLAY XAUTHORITY
     fi
 }
+
+if [ $# -gt 0 ]; then
+    die "$(usage)"
+fi
 
 # Plan A: check if the variables are already set
 exit_if_found
@@ -73,7 +70,6 @@ $(ck-list-sessions)
 EOF
 
 # Plan D: give up!
-echo "Could not detect or access the active display" >&2
 echo "DISPLAY=
 XAUTHORITY="
-exit 1
+die "Could not detect or access the active display"
